CREATE TABLE CARGOS (
	ID INTEGER NOT NULL,
	CARGOTYPE VARCHAR(64),
	NAME VARCHAR(64),
	WEIGHT INTEGER,
	EXPIRATIONDATE DATE,
	STORETEMPERATURE INTEGER,
	SIZE VARCHAR(64),
	DESCRIPTION VARCHAR(64)
	MATERIAL VARCHAR(64),
	PRIMARY KEY (ID)
);

CREATE TABLE CARRIERS (
	ID VARCHAR(64) NOT NULL,
	NAME VARCHAR(64),
	ADDRESS VARCHAR(64),
	CARRIERTYPE VARCHAR(64),
	PRIMARY KEY (ID)
);


CREATE TABLE TRANSPORTATIONS (
	ID INTEGER NOT NULL,	
	CARGOREF INTEGER NOT NULL,
	CARRIERREF INTEGER NOT NULL,
	BILLTO VARCHAR(64),
	BEGINDATE DATE,
	DESCRIPTION VARCHAR(64)
	PRIMARY KEY (ID),
	FOREIGN KEY (CARGOREF) REFERENCES CARGOS(ID),
	FOREIGN KEY (CARRIERREF) REFERENCES CARRIERS(ID)
);

